language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      install: "sudo apt-get update && sudo apt-get install -y cmake fuse libfuse-dev"
    - os: osx
      install: "brew update && sudo brew cask install osxfuse"
      sudo: required
script: "cmake . && make -j4 && ctest -V"
