language: cpp
matrix:
  include:
    - os: osx
      compiler: clang
      install: "brew update && brew cask update && brew cask install osxfuse"
      sudo: required
      script: "cmake . && make -j4 && ./securefs v && ctest -V"
    - os: linux
      dist: trusty
      sudo: required
      install: "sudo apt-get update && sudo apt-get install -y cmake fuse libfuse-dev"
      script: "cmake . && make -j4 && ./securefs v && ctest -V"
